<script setup>
import { reactive, ref } from 'vue'
import DataTable from '../components/common/DataTable.vue'
import FloatingWindow from '../components/common/FloatingWindow.vue'
import NeonPanel from '../components/common/NeonPanel.vue'
import { useAppStore } from '../stores/app'
const store=useAppStore(); const userWindow=ref(false); const teamWindow=ref(false)
const userDraft=reactive({name:'',email:'',role:'operator',status:'active',password:''}); const teamDraft=reactive({name:'',description:'',memberIds:[]})
async function saveUser(){await store.saveUser(userDraft);userWindow.value=false} async function saveTeam(){await store.saveTeam(teamDraft);teamWindow.value=false}
</script>
<template><div class="access-workspace"><div class="toolbar-row commandbar"><div><p class="section-eyebrow">Governance</p><h2 class="page-title">Access Control</h2></div><div class="chip-line"><v-btn variant="text" prepend-icon="mdi-account-group-outline" @click="teamWindow=true">Create Team</v-btn><v-btn class="glass-button" prepend-icon="mdi-account-plus-outline" @click="userWindow=true">Add User</v-btn></div></div><section class="access-banner"><div><p class="section-eyebrow">Identity Plane</p><strong>{{ store.catalog.users?.length || 0 }} local operators / {{ store.catalog.teams?.length || 0 }} access groups</strong></div><span>Shared PowerShell operations inherit team boundaries before credentials, scripts, or schedules can be exposed.</span></section><div class="content-grid"><NeonPanel class="span-7" subtitle="Operator Directory" title="Registered Users"><div class="table-pad"><DataTable :items="store.catalog.users||[]" :columns="[{key:'name',label:'Name'},{key:'email',label:'Identity'},{key:'role',label:'Role'},{key:'status',label:'State'}]" /></div></NeonPanel><NeonPanel class="span-5" subtitle="Group Registry" title="Access Teams"><div class="team-list"><article v-for="team in store.catalog.teams" :key="team.id"><v-icon icon="mdi-account-group-outline" /><div><strong>{{team.name}}</strong><span>{{team.description || 'No description'}}</span></div><v-chip variant="outlined">{{team.memberIds?.length || 0}} members</v-chip></article></div></NeonPanel></div><FloatingWindow v-model="userWindow" title="Add Operator" :width="460" :start-x="200" :start-y="110"><div class="window-form"><v-text-field v-model="userDraft.name" label="Name"/><v-text-field v-model="userDraft.email" label="Email"/><div class="two"><v-select v-model="userDraft.role" :items="['admin','operator','viewer']" label="Role"/><v-select v-model="userDraft.status" :items="['active','disabled']" label="State"/></div><v-text-field v-model="userDraft.password" label="Temporary password" type="password"/><div class="actions"><v-btn variant="text" @click="userWindow=false">Cancel</v-btn><v-btn class="glass-button" @click="saveUser">Create Operator</v-btn></div></div></FloatingWindow><FloatingWindow v-model="teamWindow" title="Create Access Team" :width="480" :start-x="490" :start-y="130"><div class="window-form"><v-text-field v-model="teamDraft.name" label="Team name"/><v-textarea v-model="teamDraft.description" label="Operational purpose" rows="3"/><v-select v-model="teamDraft.memberIds" :items="store.catalog.users" item-title="name" item-value="id" label="Members" multiple chips/><div class="actions"><v-btn variant="text" @click="teamWindow=false">Cancel</v-btn><v-btn class="glass-button" @click="saveTeam">Create Team</v-btn></div></div></FloatingWindow></div></template>
<style scoped>.access-workspace{display:grid;gap:14px}.commandbar{padding:2px 0 4px}.access-banner{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:15px 18px;border:1px solid var(--line-hot);background:linear-gradient(105deg,rgba(146,57,185,.42),rgba(44,10,74,.75))}.access-banner strong{display:block;margin-top:4px;font-family:'Share Tech Mono',monospace;color:var(--cyan)}.access-banner>span{max-width:53ch;color:var(--muted);font-size:.78rem}.table-pad{padding:14px 16px 16px}.team-list{display:grid;gap:7px;padding:14px}.team-list article{display:grid;grid-template-columns:22px 1fr auto;gap:9px;align-items:center;padding:10px;border:1px solid var(--line);background:rgba(210,90,255,.05)}.team-list .v-icon{color:var(--amber)}.team-list div{display:grid;gap:2px}.team-list span{color:var(--muted);font-size:.72rem}.window-form{display:grid;gap:12px}.two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:700px){.access-banner,.two{grid-template-columns:1fr;display:grid}.access-banner>span{max-width:none}}</style>
