<script setup>
import { computed, reactive, ref } from 'vue'
import DataTable from '../components/common/DataTable.vue'
import FloatingWindow from '../components/common/FloatingWindow.vue'
import NeonPanel from '../components/common/NeonPanel.vue'
import { useAppStore } from '../stores/app'
const store = useAppStore(); const editorOpen = ref(false)
const credentialDraft = reactive({ name: '', scope: 'personal', username: '', domainName: '', protocol: 'ssh', secret: '', teamIds: [], notes: '' })
const teams = computed(() => store.catalog.teams || [])
async function saveCredential() { await store.saveCredential(credentialDraft); editorOpen.value = false; Object.assign(credentialDraft, { name: '', scope: 'personal', username: '', domainName: '', protocol: 'ssh', secret: '', teamIds: [], notes: '' }) }
</script>
<template><div class="vault-workspace"><div class="toolbar-row commandbar"><div><p class="section-eyebrow">Security Boundary</p><h2 class="page-title">Secret Vault</h2></div><div class="chip-line"><v-chip color="secondary" variant="tonal">AES-256-GCM</v-chip><v-btn class="glass-button" prepend-icon="mdi-key-plus" @click="editorOpen = true">Store Credential</v-btn></div></div><div class="vault-metrics"><article><v-icon icon="mdi-key-variant" /><strong>{{ store.catalog.credentials?.length || 0 }}</strong><span>accessible credentials</span></article><article><v-icon icon="mdi-account-group-outline" /><strong>{{ teams.length }}</strong><span>sharing boundaries</span></article><article><v-icon icon="mdi-lock-check-outline" /><strong>SEALED</strong><span>runtime encryption state</span></article></div><NeonPanel subtitle="Credential Registry" title="Accessible Secrets"><template #actions><v-btn size="small" variant="text" prepend-icon="mdi-filter-variant">Filter</v-btn></template><div class="table-pad"><DataTable :items="store.catalog.credentials || []" :columns="[{ key: 'name', label: 'Credential' }, { key: 'scope', label: 'Scope' }, { key: 'username', label: 'Principal' }, { key: 'protocol', label: 'Transport' }, { key: 'notes', label: 'Notes' }]" /></div></NeonPanel><FloatingWindow v-model="editorOpen" title="Store Credential" :width="500" :start-x="220" :start-y="110"><div class="window-form two-col"><v-text-field v-model="credentialDraft.name" label="Credential name" class="full" /><v-select v-model="credentialDraft.scope" :items="['personal', 'shared']" label="Visibility" /><v-select v-model="credentialDraft.protocol" :items="['ssh', 'local']" label="Transport" /><v-text-field v-model="credentialDraft.username" label="Username" /><v-text-field v-model="credentialDraft.domainName" label="Domain" /><v-text-field v-model="credentialDraft.secret" type="password" label="Password / secret" class="full" /><v-select v-if="credentialDraft.scope === 'shared'" v-model="credentialDraft.teamIds" :items="teams" item-title="name" item-value="id" label="Authorized teams" multiple chips class="full" /><v-textarea v-model="credentialDraft.notes" label="Operator notes" rows="3" class="full" /><div class="actions full"><v-btn variant="text" @click="editorOpen = false">Cancel</v-btn><v-btn class="glass-button" @click="saveCredential">Seal Credential</v-btn></div></div></FloatingWindow></div></template>
<style scoped>.vault-workspace { display:grid; gap:14px; }.commandbar{padding:2px 0 4px}.vault-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.vault-metrics article{display:grid;grid-template-columns:30px 1fr;column-gap:10px;align-items:center;padding:13px;border:1px solid var(--line);background:linear-gradient(135deg,rgba(87,27,126,.78),rgba(32,8,58,.8))}.vault-metrics .v-icon{grid-row:span 2;color:var(--amber)}.vault-metrics strong{font-family:'Share Tech Mono',monospace;font-size:1.2rem}.vault-metrics span{color:var(--muted);font-size:.72rem}.table-pad{padding:14px 16px 16px}.window-form{display:grid;gap:12px}.two-col{grid-template-columns:repeat(2,minmax(0,1fr))}.full{grid-column:1/-1}.actions{display:flex;justify-content:flex-end;gap:8px}@media(max-width:620px){.vault-metrics,.two-col{grid-template-columns:1fr}.full{grid-column:auto}}</style>
