<script setup>
import { computed, reactive, ref } from 'vue'
import FloatingWindow from '../common/FloatingWindow.vue'
import { useAppStore } from '../../stores/app'

const open = defineModel({ default: false })
const store = useAppStore()
const step = ref(1)
const loading = ref(false)
const discovered = ref([])
const selectedIds = ref([])
const imported = ref(false)
const results = ref([])
const error = ref('')
const wizard = reactive({ connectorId: '', credentialId: '' })
const connectors = computed(() => store.catalog.settings.proxmox?.connectors || [])
const credentials = computed(() => (store.catalog.credentials || []).filter((credential) => credential.protocol === 'psremoting'))
const selectedMachines = computed(() => discovered.value.filter((machine) => selectedIds.value.includes(machine.id)))

function reset() { step.value = 1; discovered.value = []; selectedIds.value = []; imported.value = false; results.value = []; error.value = ''; Object.assign(wizard, { connectorId: '', credentialId: '' }) }
async function discover() { if (!wizard.connectorId) return void (error.value = 'Choose a Proxmox connector first.'); loading.value = true; error.value = ''; try { discovered.value = await store.discoverProxmox(wizard.connectorId); selectedIds.value = discovered.value.map((machine) => machine.id) } catch (requestError) { error.value = requestError.message } finally { loading.value = false } }
async function verifyConnections() { loading.value = true; error.value = ''; results.value = []; try { for (const machine of selectedMachines.value) { try { const result = await store.testMachineCandidate({ target: machine.ipAddress || machine.name, credentialId: wizard.credentialId, port: 5985 }); results.value.push({ machine, ...result }) } catch (requestError) { results.value.push({ machine, ok: false, stdout: '', stderr: requestError.message }) } } } finally { loading.value = false } }
async function importVerified() { loading.value = true; error.value = ''; try { const machineIds = results.value.filter((result) => result.ok).map((result) => result.machine.id); await store.importProxmoxSelection(wizard.connectorId, machineIds, Object.fromEntries(machineIds.map((id) => [id, wizard.credentialId]))); imported.value = true; step.value = 4 } catch (requestError) { error.value = requestError.message } finally { loading.value = false } }
function close() { open.value = false; reset() }
</script>

<template>
  <FloatingWindow v-model="open" title="Import Proxmox Machines" :width="760" :start-x="190" :start-y="90">
    <div class="wizard-shell">
      <div class="wizard-steps"><button v-for="item in [{ id: 1, label: 'Discover', icon: 'mdi-radar' }, { id: 2, label: 'Credential', icon: 'mdi-key-outline' }, { id: 3, label: 'Verify', icon: 'mdi-lan-check' }, { id: 4, label: 'Summary', icon: 'mdi-check-decagram-outline' }]" :key="item.id" type="button" :class="['wizard-step', { active: step === item.id, complete: step > item.id }]" :disabled="item.id > step" @click="step = item.id"><v-icon :icon="item.icon"/><span>{{ item.label }}</span></button></div>
      <v-alert v-if="error" type="error" density="compact" variant="tonal">{{ error }}</v-alert>
      <v-window v-model="step" class="wizard-carousel">
        <v-window-item :value="1"><section class="wizard-stage"><div class="stage-intro"><p class="section-eyebrow">Step 01 / Proxmox Inventory</p><h3>Select cluster or node-scoped guests.</h3><span>Discovery is read-only and does not create machine records.</span></div><div class="discovery-bar"><v-select v-model="wizard.connectorId" :items="connectors" item-title="name" item-value="id" label="Proxmox connector" density="compact" hide-details/><v-btn class="glass-button" :loading="loading" prepend-icon="mdi-radar" @click="discover">Discover</v-btn></div><div v-if="!connectors.length" class="empty-panel"><v-icon icon="mdi-server-network-off"/><span>Add a Proxmox connector from System Settings first.</span></div><div v-else-if="discovered.length" class="machine-list"><article v-for="machine in discovered" :key="machine.id" class="machine-row"><v-switch v-model="selectedIds" :value="machine.id" color="secondary" density="compact" hide-details/><div><strong>{{ machine.name }}</strong><span>{{ machine.node }} · {{ machine.type }} · {{ machine.powerState }}</span></div><v-chip size="x-small" variant="tonal">{{ machine.powerState }}</v-chip></article></div><div v-else class="empty-panel"><v-icon icon="mdi-radar"/><span>Choose a connector and scan its Proxmox inventory.</span></div><div class="wizard-actions"><v-btn variant="text" @click="close">Cancel</v-btn><v-btn class="glass-button" :disabled="!selectedIds.length" @click="step = 2">Assign Credentials</v-btn></div></section></v-window-item>
        <v-window-item :value="2"><section class="wizard-stage"><div class="stage-intro"><p class="section-eyebrow">Step 02 / Access Binding</p><h3>Assign a PowerShell Remoting credential.</h3><span>The selected credential is used for pre-import verification and retained for imported guests.</span></div><v-select v-model="wizard.credentialId" :items="credentials" item-title="name" item-value="id" label="Remoting credential"/><v-alert v-if="!credentials.length" type="warning" variant="tonal" density="compact">Create a PowerShell Remoting credential in Secret Vault before continuing.</v-alert><div class="wizard-actions"><v-btn variant="text" @click="step = 1">Back</v-btn><v-btn class="glass-button" :disabled="!wizard.credentialId" @click="step = 3">Verify Connections</v-btn></div></section></v-window-item>
        <v-window-item :value="3"><section class="wizard-stage"><div class="stage-intro"><p class="section-eyebrow">Step 03 / Node Verification</p><h3>Verify remote access before import.</h3><span>On a failed remoting probe, POSHinit tries SSH remediation and tests again without creating a machine record.</span></div><div v-if="!results.length" class="verify-callout"><v-icon icon="mdi-lan-connect"/><span>Ready to test {{ selectedMachines.length }} selected guest remoting endpoints.</span></div><div v-else class="verification-list"><article v-for="result in results" :key="result.machine.id" :class="['verification-row', result.ok ? 'success' : 'failed']"><v-icon :icon="result.ok ? 'mdi-check-circle-outline' : 'mdi-alert-circle-outline'"/><div><strong>{{ result.machine.name }}</strong><span>{{ result.ok ? (result.remediated ? 'PowerShell Remoting enabled through SSH and verified.' : (result.stdout || 'PowerShell Remoting connected.')) : (result.remediationError || result.stderr || 'Connectivity test failed.') }}</span></div></article></div><div class="wizard-actions"><v-btn variant="text" :disabled="loading || results.length" @click="step = 2">Back</v-btn><v-btn v-if="!results.length" class="glass-button" :loading="loading" prepend-icon="mdi-lan-check" @click="verifyConnections">Test Connections</v-btn><v-btn v-else class="glass-button" prepend-icon="mdi-arrow-right" @click="step = 4">Review Import</v-btn></div></section></v-window-item>
        <v-window-item :value="4"><section class="wizard-stage"><div class="stage-intro"><p class="section-eyebrow">Step 04 / Import Summary</p><h3>{{ imported ? 'Verified guests imported.' : 'Import verified guests.' }}</h3><span>{{ results.filter((result) => result.ok).length }} of {{ results.length }} selected guests passed. Failed targets will not be imported.</span></div><div class="verification-list"><article v-for="result in results" :key="result.machine.id" :class="['verification-row', result.ok ? 'success' : 'failed']"><v-icon :icon="result.ok ? 'mdi-check-circle-outline' : 'mdi-alert-circle-outline'"/><div><strong>{{ result.machine.name }}</strong><span>{{ result.ok ? (imported ? 'Imported into inventory' : 'Ready for inventory import') : 'Not imported: connection test failed' }}</span></div></article></div><div class="wizard-actions"><v-btn v-if="!imported" variant="text" :disabled="loading" @click="step = 3">Back</v-btn><v-btn v-if="!imported" class="glass-button" :disabled="!results.some((result) => result.ok)" :loading="loading" prepend-icon="mdi-check" @click="importVerified">Import Verified Machines</v-btn><v-btn v-else class="glass-button" prepend-icon="mdi-check" @click="close">Complete</v-btn></div></section></v-window-item>
      </v-window>
    </div>
  </FloatingWindow>
</template>

<style scoped>
.wizard-shell, .wizard-stage { display: grid; gap: 15px; }.wizard-steps { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); border: 1px solid var(--line); background: rgba(5, 13, 22, .55); }.wizard-step { display: flex; align-items: center; justify-content: center; gap: 7px; min-width: 0; padding: 10px; border: 0; border-right: 1px solid var(--line); background: transparent; color: var(--muted); font: 600 .7rem 'Share Tech Mono', monospace; letter-spacing: .04em; cursor: pointer; }.wizard-step:last-child { border-right: 0; }.wizard-step.active { color: var(--cyan); background: rgba(40, 211, 255, .1); }.wizard-step.complete { color: var(--green); }.wizard-step:disabled { cursor: default; opacity: .65; }.stage-intro { display: grid; gap: 5px; }.stage-intro p, .stage-intro h3 { margin: 0; }.stage-intro h3 { font-size: 1rem; }.stage-intro span { color: var(--muted); font-size: .78rem; }.discovery-bar { display: grid; grid-template-columns: 1fr auto; gap: 10px; align-items: center; }.machine-list, .verification-list { display: grid; max-height: 295px; overflow: auto; border: 1px solid var(--line); }.machine-row, .verification-row { display: grid; grid-template-columns: auto 1fr auto; align-items: center; gap: 10px; min-width: 0; padding: 9px 12px; border-bottom: 1px solid rgba(40, 211, 255, .1); background: rgba(40, 211, 255, .035); }.machine-row:last-child, .verification-row:last-child { border-bottom: 0; }.machine-row > div, .verification-row > div { display: grid; gap: 2px; min-width: 0; }.machine-row span, .verification-row span { overflow: hidden; color: var(--muted); font-size: .72rem; text-overflow: ellipsis; white-space: nowrap; }.verification-row { grid-template-columns: auto 1fr; }.verification-row.success { border-left: 2px solid var(--green); }.verification-row.success > .v-icon { color: var(--green); }.verification-row.failed { border-left: 2px solid #ff799b; }.verification-row.failed > .v-icon { color: #ff799b; }.empty-panel, .verify-callout { display: flex; min-height: 120px; align-items: center; justify-content: center; gap: 10px; padding: 20px; border: 1px dashed var(--line); color: var(--muted); font-size: .8rem; text-align: center; }.empty-panel .v-icon, .verify-callout .v-icon { color: var(--cyan); }.wizard-actions { display: flex; justify-content: flex-end; gap: 8px; }.wizard-carousel { min-height: 390px; } @media (max-width: 620px) { .wizard-steps, .discovery-bar { grid-template-columns: 1fr; }.wizard-step { justify-content: flex-start; border-right: 0; border-bottom: 1px solid var(--line); }.wizard-step:last-child { border-bottom: 0; }.wizard-carousel { min-height: 510px; } }
</style>
