import crypto from 'node:crypto'
import dgram from 'node:dgram'
import { nanoid } from 'nanoid'
import { all, get, nowIso, run } from '../db/client.js'
import { getStoredAuditSettings } from './settingsService.js'
import { decryptSecret } from '../utils/crypto.js'

function safe(value) { const text = JSON.stringify(value || {}); return JSON.parse(text.replace(/("(?:password|token|secret|authorization)[^"]*"\s*:\s*)"[^"]*"/gi, '$1"[redacted]"')) }
function hash(value) { return crypto.createHash('sha256').update(value).digest('hex') }
function emitSyslog(event, config) { if (!config.syslogHost) return; const message = `<134>1 ${new Date(event.occurred_at).toISOString()} poshinit - - - ${JSON.stringify(event)}`; const socket = dgram.createSocket('udp4'); socket.send(message, Number(config.syslogPort || 514), config.syslogHost, () => socket.close()) }
async function emitHttp(event, config) { if (!config.webhookUrl) return; const body = JSON.stringify(event); const signature = config.webhookToken ? crypto.createHmac('sha256', config.webhookToken).update(body).digest('hex') : ''; await fetch(config.webhookUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-POSHinit-Audit-Signature': signature }, body }).catch(() => {}) }
export function recordAudit({ actorId = null, actorType = 'user', action, resourceType, resourceId = '', outcome = 'success', before = {}, after = {}, context = {} }) { const last = get('SELECT sequence, event_hash FROM audit_events ORDER BY sequence DESC LIMIT 1'); const sequence = Number(last?.sequence || 0) + 1; const occurredAt = nowIso(); const normalized = { id: nanoid(), sequence, occurred_at: occurredAt, actor_id: actorId, actor_type: actorType, action, resource_type: resourceType, resource_id: resourceId, outcome, before_json: JSON.stringify(safe(before)), after_json: JSON.stringify(safe(after)), context_json: JSON.stringify(safe(context)), previous_hash: last?.event_hash || '' }; const eventHash = hash(`${normalized.previous_hash}|${sequence}|${occurredAt}|${actorId || ''}|${action}|${resourceType}|${resourceId}|${normalized.outcome}|${normalized.before_json}|${normalized.after_json}|${normalized.context_json}`); run(`INSERT INTO audit_events (id, sequence, occurred_at, actor_id, actor_type, action, resource_type, resource_id, outcome, before_json, after_json, context_json, previous_hash, event_hash) VALUES (@id,@sequence,@occurred_at,@actor_id,@actor_type,@action,@resource_type,@resource_id,@outcome,@before_json,@after_json,@context_json,@previous_hash,@event_hash)`, { ...normalized, event_hash: eventHash }); const event = { ...normalized, event_hash: eventHash, before: safe(before), after: safe(after), context: safe(context) }; const config = getStoredAuditSettings() || {}; config.webhookToken = decryptSecret(config.webhookTokenEncrypted); try { emitSyslog(event, config); void emitHttp(event, config) } catch { /* Audit persistence must not be blocked by SIEM availability. */ } return event }
export function listAuditEvents(query = '') { const pattern = `%${query}%`; return all('SELECT * FROM audit_events WHERE action LIKE ? OR resource_type LIKE ? OR resource_id LIKE ? OR context_json LIKE ? ORDER BY sequence DESC LIMIT 500', [pattern, pattern, pattern, pattern]).map((event) => ({ ...event, before: JSON.parse(event.before_json), after: JSON.parse(event.after_json), context: JSON.parse(event.context_json) })) }
export function verifyAuditChain() { const events = all('SELECT * FROM audit_events ORDER BY sequence ASC'); let previous = ''; const invalid = events.find((event) => { const expected = hash(`${previous}|${event.sequence}|${event.occurred_at}|${event.actor_id || ''}|${event.action}|${event.resource_type}|${event.resource_id || ''}|${event.outcome}|${event.before_json}|${event.after_json}|${event.context_json}`); previous = event.event_hash; return expected !== event.event_hash }); return { valid: !invalid, events: events.length, invalidSequence: invalid?.sequence || null, head: previous || null } }
