import { nanoid } from 'nanoid'
import { all, get, nowIso, run } from '../db/client.js'
import { decryptSecret, encryptSecret } from '../utils/crypto.js'

const parse = (value, fallback = {}) => { try { return JSON.parse(value || '') } catch { return fallback } }
const lookup = (value, path) => String(path || '').split('.').filter(Boolean).reduce((current, key) => current?.[key], value)
const kinds = new Set(['servicenow', 'rest', 'csv'])
function publicSource(source) { const config = parse(source.config_json); delete config.authTokenEncrypted; delete config.passwordEncrypted; return { ...source, enabled: Boolean(source.enabled), config, mapping: parse(source.mapping_json), authConfigured: Boolean(parse(source.config_json).authTokenEncrypted || parse(source.config_json).passwordEncrypted) } }
export function listCmdbEnrichmentSources() { return all('SELECT * FROM cmdb_enrichment_sources ORDER BY name').map(publicSource) }
export function listCmdbEnrichmentRuns(sourceId) { return all('SELECT * FROM cmdb_enrichment_runs WHERE source_id = ? ORDER BY started_at DESC LIMIT 50', [sourceId]) }
export function saveCmdbEnrichmentSource(payload = {}) {
  const id = payload.id || nanoid(); const existing = payload.id ? get('SELECT * FROM cmdb_enrichment_sources WHERE id = ?', [payload.id]) : null; const kind = kinds.has(payload.kind) ? payload.kind : 'rest'; const previous = parse(existing?.config_json); const config = { url: String(payload.config?.url || '').trim().replace(/\/$/, ''), table: String(payload.config?.table || 'cmdb_ci_server').trim(), recordsPath: String(payload.config?.recordsPath || 'result').trim(), csvText: String(payload.config?.csvText || previous.csvText || ''), authType: payload.config?.authType === 'basic' ? 'basic' : 'bearer', username: String(payload.config?.username || '').trim(), passwordEncrypted: payload.config?.password ? encryptSecret(payload.config.password) : previous.passwordEncrypted || '', authTokenEncrypted: payload.config?.authToken ? encryptSecret(payload.config.authToken) : previous.authTokenEncrypted || '' }; if (kind !== 'csv' && !config.url) throw new Error('A source URL is required'); if (kind === 'csv' && !config.csvText.trim()) throw new Error('Paste CSV content before saving this source'); const mapping = payload.mapping && typeof payload.mapping === 'object' ? payload.mapping : {}; const timestamp = nowIso(); run(`INSERT INTO cmdb_enrichment_sources (id, name, kind, enabled, match_field, config_json, mapping_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET name=excluded.name, kind=excluded.kind, enabled=excluded.enabled, match_field=excluded.match_field, config_json=excluded.config_json, mapping_json=excluded.mapping_json, updated_at=excluded.updated_at`, [id, String(payload.name || '').trim() || 'CMDB source', kind, Number(payload.enabled !== false), ['name', 'fqdn', 'ip'].includes(payload.matchField) ? payload.matchField : 'fqdn', JSON.stringify(config), JSON.stringify(mapping), existing?.created_at || timestamp, timestamp]); return publicSource(get('SELECT * FROM cmdb_enrichment_sources WHERE id = ?', [id]))
}
export function deleteCmdbEnrichmentSource(id) { return run('DELETE FROM cmdb_enrichment_sources WHERE id = ?', [id]).changes > 0 }
function parseCsv(text) { const [header, ...lines] = String(text || '').trim().split(/\r?\n/); const columns = (header || '').split(',').map((item) => item.trim()); return lines.filter(Boolean).map((line) => Object.fromEntries(columns.map((column, index) => [column, line.split(',')[index]?.trim() || '']))) }
async function sourceRecords(source) { const config = parse(source.config_json); if (source.kind === 'csv') return parseCsv(config.csvText); const headers = { Accept: 'application/json' }; const token = decryptSecret(config.authTokenEncrypted); const password = decryptSecret(config.passwordEncrypted); if (config.authType === 'basic' && config.username && password) headers.Authorization = `Basic ${Buffer.from(`${config.username}:${password}`).toString('base64')}`; else if (token) headers.Authorization = `Bearer ${token}`; const url = source.kind === 'servicenow' ? `${config.url}/api/now/table/${encodeURIComponent(config.table)}?sysparm_limit=10000` : config.url; const response = await fetch(url, { headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message || `CMDB request failed with status ${response.status}`); const records = lookup(body, config.recordsPath) || body; return Array.isArray(records) ? records : [] }
function machineMatch(machine, matchField, identity) { const value = matchField === 'ip' ? machine.ip_address : machine[matchField]; return String(value || '').toLowerCase() === String(identity || '').toLowerCase() }
export async function syncCmdbEnrichmentSource(id) { const { observeOperation } = await import('../observability.js'); return observeOperation('integration', 'cmdb_enrichment', { sourceId: id }, async () => { const source = get('SELECT * FROM cmdb_enrichment_sources WHERE id = ?', [id]); if (!source) throw new Error('CMDB enrichment source was not found'); const runId = nanoid(); const started = nowIso(); run('INSERT INTO cmdb_enrichment_runs (id, source_id, status, started_at) VALUES (?, ?, ?, ?)', [runId, id, 'running', started]); try { const records = await sourceRecords(source); const mapping = parse(source.mapping_json); let enriched = 0; for (const record of records) { const identity = lookup(record, mapping.identity || source.match_field); const machine = all('SELECT * FROM machines').find((item) => machineMatch(item, source.match_field, identity)); if (!machine) continue; const hostFacts = { ...parse(machine.host_facts_json), ...Object.fromEntries(Object.entries(mapping.hostFacts || {}).map(([key, path]) => [key, lookup(record, path)]).filter(([, value]) => value != null && value !== '')) }; const customFacts = { ...parse(machine.custom_facts_json), ...Object.fromEntries(Object.entries(mapping.customFacts || {}).map(([key, path]) => [key, lookup(record, path)]).filter(([, value]) => value != null && value !== '')) }; const criticality = lookup(record, mapping.criticality) || machine.criticality; const service = lookup(record, mapping.businessService) || machine.business_service; const maintenance = lookup(record, mapping.maintenanceWindow) || parse(machine.maintenance_window_json); run('UPDATE machines SET host_facts_json = ?, custom_facts_json = ?, criticality = ?, business_service = ?, maintenance_window_json = ?, updated_at = ? WHERE id = ?', [JSON.stringify(hostFacts), JSON.stringify(customFacts), ['low', 'standard', 'high', 'critical'].includes(String(criticality)) ? criticality : machine.criticality, String(service || ''), JSON.stringify(maintenance || {}), nowIso(), machine.id]); enriched += 1 }
    run("UPDATE cmdb_enrichment_sources SET last_sync_at = ?, health_state = 'healthy', last_error = NULL, updated_at = ? WHERE id = ?", [nowIso(), nowIso(), id]); run("UPDATE cmdb_enrichment_runs SET status = 'completed', finished_at = ?, records_read = ?, nodes_enriched = ? WHERE id = ?", [nowIso(), records.length, enriched, runId]); return { id: runId, recordsRead: records.length, nodesEnriched: enriched }
  } catch (error) { const message = error.message || 'CMDB enrichment failed'; run("UPDATE cmdb_enrichment_sources SET health_state = 'error', last_error = ?, updated_at = ? WHERE id = ?", [message, nowIso(), id]); run("UPDATE cmdb_enrichment_runs SET status = 'failed', finished_at = ?, error_message = ? WHERE id = ?", [nowIso(), message, runId]); throw error } }) }
