import crypto from 'node:crypto'
import bcrypt from 'bcryptjs'
import { get, nowIso, run } from '../db/client.js'
import { decryptSecret, encryptSecret } from '../utils/crypto.js'
import { recordAudit } from './auditService.js'

const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
function base32(bytes) { let bits = ''; for (const byte of bytes) bits += byte.toString(2).padStart(8, '0'); return (bits.match(/.{1,5}/g) || []).map((part) => alphabet[Number.parseInt(part.padEnd(5, '0'), 2)]).join('') }
function base32Bytes(value) { let bits = ''; for (const char of String(value).replace(/=|\s/g, '').toUpperCase()) { const index = alphabet.indexOf(char); if (index >= 0) bits += index.toString(2).padStart(5, '0') } return Buffer.from((bits.match(/.{8}/g) || []).map((part) => Number.parseInt(part, 2))) }
function totp(secret, timestamp = Date.now()) { const counter = Buffer.alloc(8); counter.writeBigUInt64BE(BigInt(Math.floor(timestamp / 30000))); const digest = crypto.createHmac('sha1', base32Bytes(secret)).update(counter).digest(); const offset = digest[digest.length - 1] & 15; return String(((digest.readUInt32BE(offset) & 0x7fffffff) % 1_000_000)).padStart(6, '0') }
export function verifyTotp(secret, code) { return [-1, 0, 1].some((offset) => crypto.timingSafeEqual(Buffer.from(totp(secret, Date.now() + offset * 30000)), Buffer.from(String(code || '').padStart(6, '0')))) }
function publicProfile(row) { return { id: row.id, name: row.name, email: row.email, role: row.role, entraEnabled: Boolean(row.entra_enabled), theme: ['purple', 'ocean-wave', 'moderno'].includes(row.theme) ? row.theme : 'purple', mfaEnabled: Boolean(row.mfa_enabled) } }
export function getProfile(userId) { return publicProfile(get('SELECT * FROM users WHERE id=?', [userId])) }
export function changePassword(userId, payload = {}) { const user = get('SELECT * FROM users WHERE id=?', [userId]); if (!user || !bcrypt.compareSync(String(payload.currentPassword || ''), user.password_hash)) { const error = new Error('Current password is incorrect'); error.statusCode = 400; throw error } if (String(payload.newPassword || '').length < 12) { const error = new Error('Use a password of at least 12 characters'); error.statusCode = 400; throw error } run('UPDATE users SET password_hash=?, updated_at=? WHERE id=?', [bcrypt.hashSync(payload.newPassword, 10), nowIso(), userId]); recordAudit({ actorId: userId, action: 'profile.password.changed', resourceType: 'user', resourceId: userId }); return { changed: true } }
export function beginMfaEnrollment(userId) { const secret = base32(crypto.randomBytes(20)); const user = get('SELECT email FROM users WHERE id=?', [userId]); const issuer = 'POSHinit'; return { secret, otpauthUri: `otpauth://totp/${encodeURIComponent(`${issuer}:${user.email}`)}?secret=${secret}&issuer=${encodeURIComponent(issuer)}&algorithm=SHA1&digits=6&period=30` } }
export function confirmMfaEnrollment(userId, payload = {}) { if (!verifyTotp(payload.secret, payload.code)) { const error = new Error('The authenticator code is invalid'); error.statusCode = 400; throw error } run('UPDATE users SET mfa_enabled=1, mfa_secret_encrypted=?, updated_at=? WHERE id=?', [encryptSecret(payload.secret), nowIso(), userId]); recordAudit({ actorId: userId, action: 'profile.mfa.enrolled', resourceType: 'user', resourceId: userId }); return getProfile(userId) }
export function disableMfa(userId, payload = {}) { const user = get('SELECT * FROM users WHERE id=?', [userId]); if (!bcrypt.compareSync(String(payload.currentPassword || ''), user.password_hash)) { const error = new Error('Current password is incorrect'); error.statusCode = 400; throw error } run("UPDATE users SET mfa_enabled=0, mfa_secret_encrypted='', updated_at=? WHERE id=?", [nowIso(), userId]); recordAudit({ actorId: userId, action: 'profile.mfa.disabled', resourceType: 'user', resourceId: userId }); return getProfile(userId) }
export function saveTheme(userId, theme) { const value = ['purple', 'ocean-wave', 'moderno'].includes(theme) ? theme : 'purple'; run('UPDATE users SET theme=?, updated_at=? WHERE id=?', [value, nowIso(), userId]); recordAudit({ actorId: userId, action: 'profile.theme.changed', resourceType: 'user', resourceId: userId, context: { theme: value } }); return getProfile(userId) }
export function validMfaForUser(user, code) { return !user.mfa_enabled || verifyTotp(decryptSecret(user.mfa_secret_encrypted), code) }
