import { nanoid } from 'nanoid'
import { all, get, nowIso, run, transaction } from '../db/client.js'

const profiles = [
  { name: 'Development', type: 'dev', protected: false, approval: false },
  { name: 'Test', type: 'test', protected: false, approval: false },
  { name: 'Production', type: 'prod', protected: true, approval: true },
]

function mapEnvironment(environment) { return { ...environment, isProtected: Boolean(environment.is_protected), requireApproval: Boolean(environment.require_approval) } }
export function listProjects() { return all(`SELECT p.*, o.name AS organization_name, COUNT(e.id) AS environment_count FROM projects p JOIN organizations o ON o.id = p.organization_id LEFT JOIN environments e ON e.project_id = p.id GROUP BY p.id ORDER BY o.name, p.name`).map((project) => ({ ...project, environments: all('SELECT * FROM environments WHERE project_id = ? ORDER BY CASE environment_type WHEN \'dev\' THEN 1 WHEN \'test\' THEN 2 WHEN \'prod\' THEN 3 ELSE 4 END, name', [project.id]).map(mapEnvironment) })) }
export function saveProject(payload = {}) { const id = payload.id || nanoid(); const timestamp = nowIso(); const existing = payload.id ? get('SELECT * FROM projects WHERE id = ?', [payload.id]) : null; const organizationId = payload.organizationId || existing?.organization_id || 'org-default'; if (!get('SELECT id FROM organizations WHERE id = ?', [organizationId])) throw new Error('Organization was not found'); transaction(() => { run(`INSERT INTO projects (id, organization_id, name, description, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id, name=excluded.name, description=excluded.description, updated_at=excluded.updated_at`, [id, organizationId, String(payload.name || '').trim() || 'Untitled Project', String(payload.description || '').trim(), existing?.created_at || timestamp, timestamp]); if (!existing) profiles.forEach((profile) => run('INSERT INTO environments (id, project_id, name, environment_type, is_protected, require_approval, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)', [nanoid(), id, profile.name, profile.type, Number(profile.protected), Number(profile.approval), timestamp, timestamp])) }); return listProjects().find((project) => project.id === id) }
export function saveEnvironment(payload = {}) { const id = payload.id || nanoid(); const existing = payload.id ? get('SELECT * FROM environments WHERE id = ?', [payload.id]) : null; const projectId = payload.projectId || existing?.project_id; if (!get('SELECT id FROM projects WHERE id = ?', [projectId])) throw new Error('Project was not found'); const type = ['dev', 'test', 'prod', 'custom'].includes(payload.environmentType) ? payload.environmentType : 'custom'; const timestamp = nowIso(); run(`INSERT INTO environments (id, project_id, name, environment_type, is_protected, require_approval, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id, name=excluded.name, environment_type=excluded.environment_type, is_protected=excluded.is_protected, require_approval=excluded.require_approval, updated_at=excluded.updated_at`, [id, projectId, String(payload.name || '').trim() || 'Environment', type, Number(Boolean(payload.isProtected)), Number(Boolean(payload.requireApproval)), existing?.created_at || timestamp, timestamp]); return mapEnvironment(get('SELECT * FROM environments WHERE id = ?', [id])) }
export function deleteProject(id) { if (id === 'project-default') throw new Error('The default project cannot be deleted'); return run('DELETE FROM projects WHERE id = ?', [id]).changes > 0 }
export function projectHierarchy() { return { projects: listProjects(), organizations: all('SELECT * FROM organizations ORDER BY name'), environments: all('SELECT * FROM environments ORDER BY name').map(mapEnvironment) } }
