import https from 'node:https'
import { nanoid } from 'nanoid'
import { get } from '../db/client.js'
import { decryptSecret, encryptSecret } from '../utils/crypto.js'
import { saveGroup } from './groupService.js'
import { saveMachine } from './machineService.js'
import { getSettings, saveSettings } from './settingsService.js'

function baseUrl(value) {
  const raw = String(value || '').trim().replace(/\/$/, '')
  if (!raw) return ''
  const url = new URL(/^https?:\/\//i.test(raw) ? raw : `https://${raw}`)
  return url.port ? url.toString().replace(/\/$/, '') : `${url.toString().replace(/\/$/, '')}:8006`
}
function proxmoxFetch(url, options, ignoreTlsErrors) {
  if (!ignoreTlsErrors) return fetch(url, options)
  return new Promise((resolve, reject) => { const request = https.request(url, { method: options.method || 'GET', headers: options.headers, rejectUnauthorized: false }, (response) => { const chunks = []; response.on('data', (chunk) => chunks.push(chunk)); response.on('end', () => { const body = Buffer.concat(chunks).toString('utf8'); resolve({ ok: response.statusCode >= 200 && response.statusCode < 300, status: response.statusCode, json: async () => JSON.parse(body) }) }) }); request.on('error', reject); request.end() })
}
export function normalizeProxmoxConnectors(settings = {}) { return Array.isArray(settings.connectors) ? settings.connectors : [] }
export function normalizeProxmoxMachine(item = {}) { return { id: item.id || `${item.node || 'node'}:${item.vmid}`, name: item.name || `${item.type || 'vm'}-${item.vmid}`, node: item.node || '', guestOs: item.type === 'lxc' ? 'Linux container' : '', ipAddress: '', powerState: item.status || 'unknown', type: item.type || 'qemu' } }
function resolve(settings, id) { const saved = normalizeProxmoxConnectors(settings).find((connector) => connector.id === id); if (!saved?.baseUrl || !saved?.apiTokenEncrypted) throw new Error('Proxmox connector settings are incomplete'); if (saved.kind === 'node' && !saved.nodeName) throw new Error('A Proxmox node name is required for a node-scoped connector'); return { ...saved, apiToken: decryptSecret(saved.apiTokenEncrypted) } }
async function inventory(connector) { const root = baseUrl(connector.baseUrl); const resourceType = connector.kind === 'node' ? (connector.resourceType === 'lxc' ? 'lxc' : 'qemu') : (['vm', 'qemu', 'lxc'].includes(connector.resourceType) ? connector.resourceType : 'vm'); const endpoint = connector.kind === 'node' ? `/api2/json/nodes/${encodeURIComponent(connector.nodeName)}/${resourceType}` : `/api2/json/cluster/resources?type=${resourceType}`; const apiToken = connector.apiToken.startsWith('PVEAPIToken=') ? connector.apiToken : `PVEAPIToken=${connector.apiToken}`; const response = await proxmoxFetch(`${root}${endpoint}`, { headers: { Authorization: apiToken } }, connector.ignoreTlsErrors); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.errors ? JSON.stringify(payload.errors) : `Proxmox inventory request failed with status ${response.status}`); return (payload.data || []).map((item) => normalizeProxmoxMachine({ ...item, type: item.type || resourceType })) }
function importValues(connector, values, credentialIds = {}) { const imported = values.map((item) => { const ref = `${connector.id}:${item.id}`; const existing = get('SELECT id FROM machines WHERE source_type = ? AND source_ref = ?', ['proxmox', ref]); return saveMachine({ id: existing?.id, name: item.name, fqdn: item.name, ipAddress: item.ipAddress, notes: `Imported from Proxmox ${connector.name} · ${item.node || 'cluster'} · ${item.type} · ${item.powerState}`, osFamily: /windows/i.test(item.guestOs) ? 'windows' : 'linux', transport: 'psremoting', port: 5985, credentialId: credentialIds[item.id] || null, sourceType: 'proxmox', sourceRef: ref }) }); if (connector.autoImportGroupId) saveGroup({ id: connector.autoImportGroupId, name: connector.autoImportGroupName || `Imported ${connector.name} Nodes`, description: `Machines imported from Proxmox ${connector.name}.`, machineIds: imported.map((machine) => machine.id) }); return imported }
export async function discoverProxmoxMachines(settings, id) { return inventory(resolve(settings, id)) }
export async function importProxmoxSelection(settings, id, machineIds, credentialIds) { const connector = resolve(settings, id); const selected = new Set(machineIds || []); return importValues(connector, (await inventory(connector)).filter((machine) => selected.has(machine.id)), credentialIds) }
export function saveProxmoxSettings(payload = {}) { const prior = normalizeProxmoxConnectors(getSettings().proxmox); const connectors = (payload.connectors || []).map((item) => { const previous = prior.find((connector) => connector.id === item.id); const kind = item.kind === 'node' ? 'node' : 'cluster'; const token = String(item.apiToken || '').trim(); return { id: item.id || nanoid(), name: String(item.name || 'Proxmox').trim(), kind, baseUrl: baseUrl(item.baseUrl), nodeName: String(item.nodeName || '').trim(), resourceType: kind === 'node' ? (item.resourceType === 'lxc' ? 'lxc' : 'qemu') : (['vm', 'qemu', 'lxc'].includes(item.resourceType) ? item.resourceType : 'vm'), apiTokenEncrypted: token ? encryptSecret(token) : previous?.apiTokenEncrypted || '', ignoreTlsErrors: Boolean(item.ignoreTlsErrors), autoImportGroupId: item.autoImportGroupId || '' } }); const saved = saveSettings('proxmox', { connectors }); return { ...saved, connectors: connectors.map(({ apiTokenEncrypted, ...connector }) => ({ ...connector, apiTokenConfigured: Boolean(apiTokenEncrypted) })) } }
