import crypto from 'node:crypto'
import { all, get, nowIso } from '../db/client.js'
import { redactOutput } from './outputRedactionService.js'
import { recordAudit } from './auditService.js'

const ageHours = (value) => value ? (Date.now() - new Date(value).getTime()) / 3600000 : Infinity
const item = (kind, severity, title, summary, evidence, action) => ({ id: crypto.createHash('sha256').update(`${kind}:${JSON.stringify(evidence)}`).digest('hex').slice(0, 16), kind, severity, title, summary, evidence, action, source: 'deterministic-rules', generatedAt: nowIso() })
function parse(value, fallback = {}) { try { return JSON.parse(value || '') } catch { return fallback } }

export function listRecommendations() {
  const findings = []
  all(`SELECT c.id,c.name,m.id AS machine_id,m.name AS machine_name,m.last_tested_at,m.last_test_output FROM credentials c JOIN machines m ON m.credential_id=c.id WHERE m.last_test_status='failed'`).forEach((row) => findings.push(item('failing-credential', 'high', `Credential ${row.name} is failing`, `${row.machine_name} failed its latest connection test with this credential.`, { credentialId: row.id, machineId: row.machine_id, testedAt: row.last_tested_at, output: redactOutput(row.last_test_output || '') }, { label: 'Test node connection', href: '/inventory' })))
  all("SELECT id,name,last_synced_at FROM deployment_groups WHERE group_type='dynamic'").filter((row) => ageHours(row.last_synced_at) > 24).forEach((row) => findings.push(item('stale-dynamic-group', 'medium', `Dynamic group ${row.name} is stale`, `Its membership has not synchronized in over 24 hours.`, { groupId: row.id, lastSyncedAt: row.last_synced_at }, { label: 'Review target collection', href: '/inventory' })))
  all(`SELECT m.id,m.name,COUNT(*) AS failures,MAX(e.finished_at) AS last_failure FROM executions e JOIN machines m ON m.id=e.machine_id WHERE e.status IN ('failed','timed_out') AND e.created_at >= datetime('now','-7 days') GROUP BY m.id HAVING COUNT(*) >= 3`).forEach((row) => findings.push(item('repeated-target-failure', 'high', `${row.name} has repeated execution failures`, `${row.failures} failed or timed-out runs were recorded in the last seven days.`, { machineId: row.id, failures: row.failures, lastFailure: row.last_failure }, { label: 'Inspect node history', href: '/inventory' })))
  all('SELECT c.id,c.name FROM credentials c LEFT JOIN machines m ON m.credential_id=c.id WHERE m.id IS NULL').forEach((row) => findings.push(item('unused-secret', 'low', `Secret ${row.name} is unused`, `No managed node currently references this credential.`, { credentialId: row.id }, { label: 'Review Secret Vault', href: '/vault' })))
  all(`SELECT s.id,s.name,AVG((julianday(e.finished_at)-julianday(e.started_at))*86400000) AS duration_ms,COUNT(*) AS runs FROM executions e JOIN library_entries s ON s.id=e.script_id WHERE e.finished_at IS NOT NULL GROUP BY s.id HAVING COUNT(*) >= 3 AND AVG((julianday(e.finished_at)-julianday(e.started_at))*86400000) > 300000`).forEach((row) => findings.push(item('slow-runbook', 'medium', `${row.name} is consistently slow`, `Average duration is ${Math.round(row.duration_ms / 1000)} seconds across ${row.runs} runs.`, { scriptId: row.id, averageMs: Math.round(row.duration_ms), runs: row.runs }, { label: 'Open Script Studio', href: '/editor' })))
  all('SELECT id,name,graph_json FROM workflow_templates').forEach((template) => parse(template.graph_json, { nodes: [] }).nodes.filter((node) => node.type === 'runbook' && !node.config?.timeoutSeconds).forEach((node) => findings.push(item('missing-timeout', 'medium', `${template.name}: ${node.label || node.id} has no timeout`, `The runbook node relies on the global default rather than an explicit workflow timeout.`, { workflowId: template.id, nodeId: node.id }, { label: 'Set node timeout', href: '/workflows' }))))
  all(`SELECT s.id,s.name,g.id AS group_id,g.name AS group_name,COUNT(gm.machine_id) AS target_count FROM schedules s JOIN schedule_targets st ON st.schedule_id=s.id AND st.target_type='group' JOIN deployment_groups g ON g.id=st.target_id LEFT JOIN deployment_group_machines gm ON gm.group_id=g.id GROUP BY s.id,g.id HAVING COUNT(gm.machine_id) > 25`).forEach((row) => findings.push(item('risky-broad-target', 'high', `${row.name} targets ${row.target_count} nodes`, `Deployment group ${row.group_name} exceeds the broad-target safety threshold.`, { scheduleId: row.id, groupId: row.group_id, targetCount: row.target_count }, { label: 'Review schedule targets', href: '/scheduler' })))
  return findings.sort((left, right) => ({ high: 0, medium: 1, low: 2 }[left.severity] - { high: 0, medium: 1, low: 2 }[right.severity]))
}

export function aiAssistPreview(recommendationId, userId) {
  const finding = listRecommendations().find((entry) => entry.id === recommendationId); if (!finding) throw new Error('Recommendation was not found')
  const preview = { recommendationId, enabled: false, status: 'opt-in-required', provenance: { generator: 'POSHinit deterministic recommendation engine', generatedAt: nowIso(), evidenceSource: finding.source, redaction: 'Output and evidence text are redacted before any optional AI provider request.' }, redactedContext: { kind: finding.kind, title: finding.title, summary: redactOutput(finding.summary), evidence: JSON.parse(redactOutput(JSON.stringify(finding.evidence))) }, requiresHumanConfirmation: true }
  recordAudit({ actorId: userId, action: 'recommendation.ai_preview', resourceType: 'recommendation', resourceId: recommendationId, context: { status: preview.status, provenance: preview.provenance } }); return preview
}
export function confirmRecommendation(recommendationId, userId, note = '') { const finding = listRecommendations().find((entry) => entry.id === recommendationId); if (!finding) throw new Error('Recommendation was not found'); recordAudit({ actorId: userId, action: 'recommendation.confirmed', resourceType: 'recommendation', resourceId: recommendationId, context: { kind: finding.kind, note: redactOutput(note), humanConfirmed: true } }); return { confirmed: true, recommendationId, confirmedAt: nowIso() } }
