import https from 'node:https'
import { nanoid } from 'nanoid'
import { get } from '../db/client.js'
import { decryptSecret, encryptSecret } from '../utils/crypto.js'
import { saveGroup } from './groupService.js'
import { saveMachine } from './machineService.js'
import { getSettings, saveSettings } from './settingsService.js'

function baseUrl(value) { const raw = String(value || '').trim().replace(/\/$/, ''); return raw ? (/^https?:\/\//i.test(raw) ? raw : `https://${raw}`) : '' }
async function rpc(url, method, params, ignoreTlsErrors) {
  const body = JSON.stringify({ jsonrpc: '2.0', id: nanoid(), method, params })
  const request = ignoreTlsErrors ? new Promise((resolve, reject) => { const call = https.request(`${baseUrl(url)}/jsonrpc`, { method: 'POST', headers: { 'content-type': 'application/json', 'content-length': Buffer.byteLength(body) }, rejectUnauthorized: false }, (response) => { const chunks = []; response.on('data', (chunk) => chunks.push(chunk)); response.on('end', () => resolve({ ok: response.statusCode >= 200 && response.statusCode < 300, json: async () => JSON.parse(Buffer.concat(chunks).toString('utf8')) })) }); call.on('error', reject); call.end(body) }) : fetch(`${baseUrl(url)}/jsonrpc`, { method: 'POST', headers: { 'content-type': 'application/json' }, body })
  const response = await request; const payload = await response.json().catch(() => ({})); if (!response.ok || payload.error) throw new Error(payload.error?.message || `XenAPI ${method} failed`); if (payload.result?.Status === 'Failure') throw new Error(`XenAPI ${method}: ${(payload.result.ErrorDescription || []).join(' ')}`); return payload.result?.Value ?? payload.result
}
export function normalizeXenServerConnectors(settings = {}) { return Array.isArray(settings.connectors) ? settings.connectors : [] }
export function normalizeXenServerMachine(record = {}, id = '') { const metrics = record.guest_metrics?.['other_config'] || record.guest_metrics?.other_config || {}; const networks = record.guest_metrics?.networks || {}; const ipAddress = Object.values(networks).find((value) => /^\d{1,3}(\.\d{1,3}){3}$/.test(String(value))) || ''; const os = record.guest_metrics?.os_version?.name || record.other_config?.['os-name'] || ''; return { id, name: record.name_label || id, guestOs: os, ipAddress, powerState: record.power_state || 'unknown', pool: record.resident_on || '', type: record.is_control_domain ? 'control-domain' : 'vm', metrics } }
function resolve(settings, id) { const connector = normalizeXenServerConnectors(settings).find((item) => item.id === id); if (!connector?.baseUrl || !connector.username || !connector.passwordEncrypted) throw new Error('XenServer connector settings are incomplete'); return { ...connector, password: decryptSecret(connector.passwordEncrypted) } }
async function inventory(connector) { const session = await rpc(connector.baseUrl, 'session.login_with_password', [connector.username, connector.password, '1.0', 'POSHinit'], connector.ignoreTlsErrors); try { const [records, guestMetrics] = await Promise.all([rpc(connector.baseUrl, 'VM.get_all_records', [session], connector.ignoreTlsErrors), rpc(connector.baseUrl, 'VM_guest_metrics.get_all_records', [session], connector.ignoreTlsErrors)]); return Object.entries(records || {}).map(([id, record]) => normalizeXenServerMachine({ ...record, guest_metrics: guestMetrics?.[record.guest_metrics] || {} }, id)).filter((machine) => machine.name && machine.type !== 'control-domain' && !/^Control domain/i.test(machine.name)) } finally { await rpc(connector.baseUrl, 'session.logout', [session], connector.ignoreTlsErrors).catch(() => {}) } }
function importValues(connector, values, credentialIds = {}) { const imported = values.map((item) => { const sourceRef = `${connector.id}:${item.id}`; const existing = get('SELECT id FROM machines WHERE source_type=? AND source_ref=?', ['xenserver', sourceRef]); return saveMachine({ id: existing?.id, name: item.name, fqdn: item.name, ipAddress: item.ipAddress, notes: `Imported from XenServer/XCP-ng ${connector.name} · ${item.powerState}`, osFamily: /windows/i.test(item.guestOs) ? 'windows' : 'linux', transport: 'psremoting', port: 5985, credentialId: credentialIds[item.id] || null, sourceType: 'xenserver', sourceRef }) }); if (connector.autoImportGroupId) saveGroup({ id: connector.autoImportGroupId, name: connector.autoImportGroupName || `Imported ${connector.name} Nodes`, description: `Machines imported from XenServer/XCP-ng ${connector.name}.`, machineIds: imported.map((machine) => machine.id) }); return imported }
export async function discoverXenServerMachines(settings, id) { return inventory(resolve(settings, id)) }
export async function importXenServerSelection(settings, id, machineIds, credentialIds) { const connector = resolve(settings, id); const selected = new Set(machineIds || []); return importValues(connector, (await inventory(connector)).filter((machine) => selected.has(machine.id)), credentialIds) }
export function saveXenServerSettings(payload = {}) { const current = normalizeXenServerConnectors(getSettings().xenserver); const connectors = (payload.connectors || []).map((item) => { const previous = current.find((connector) => connector.id === item.id); const password = String(item.passwordPlain || '').trim(); return { id: item.id || nanoid(), name: String(item.name || 'XenServer Pool').trim(), baseUrl: baseUrl(item.baseUrl), username: String(item.username || '').trim(), passwordEncrypted: password ? encryptSecret(password) : previous?.passwordEncrypted || '', ignoreTlsErrors: Boolean(item.ignoreTlsErrors), autoImportGroupId: item.autoImportGroupId || '', autoImportGroupName: item.autoImportGroupName || '' } }); const saved = saveSettings('xenserver', { connectors }); return { ...saved, connectors: connectors.map(({ passwordEncrypted, ...connector }) => ({ ...connector, passwordConfigured: Boolean(passwordEncrypted) })) } }
